"""Add image field to Product model

Revision ID: 53ed8d86f62f
Revises: b11eddd06155
Create Date: 2024-10-09 14:30:46.591632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53ed8d86f62f'
down_revision: Union[str, None] = 'b11eddd06155'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image', sa.String(length=250), nullable=True))
    op.create_index(op.f('ix_products_image'), 'products', ['image'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_image'), table_name='products')
    op.drop_column('products', 'image')
    # ### end Alembic commands ###
