"""Add price field to Product model

Revision ID: b11eddd06155
Revises: 
Create Date: 2024-10-09 13:18:31.592678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b11eddd06155'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=True)
    op.alter_column('categories', 'description',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=250),
               existing_nullable=True)
    op.create_index(op.f('ix_categories_description'), 'categories', ['description'], unique=False)
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.alter_column('products', 'name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=True)
    op.alter_column('products', 'description',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=250),
               existing_nullable=True)
    op.alter_column('products', 'price',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.create_index(op.f('ix_products_description'), 'products', ['description'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_price'), 'products', ['price'], unique=False)
    op.drop_constraint('products_ibfk_1', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_ibfk_1', 'products', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_products_price'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_description'), table_name='products')
    op.alter_column('products', 'price',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('products', 'description',
               existing_type=sa.String(length=250),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('products', 'name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_description'), table_name='categories')
    op.alter_column('categories', 'description',
               existing_type=sa.String(length=250),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('categories', 'name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
