version: '3.8'

services:
  web:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL = mysql+pymysql://isadev95:domont@isadev95.mysql.pythonanywhere-services.com:3306/hairdb

      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mysql_db
      - mongo
    volumes:
      - ./api:/app

  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: domont  # Variable d'environnement
      MYSQL_DATABASE: hairdb  # Variable d'environnement
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
      start_period: 30s


  mongo:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_app
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://web:8000
    depends_on:
      - web

  test:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: fastapi_test
    depends_on:
      - mysql_db
      - mongo
    environment:
      - DATABASE_URL= mysql+pymysql://isadev95:domont@isadev95.mysql.pythonanywhere-services.com:3306/hairdb
      - MONGO_URI=mongodb://mongo:27017
    volumes:
      - ./api:/app
    command: ["pytest", "/app"]

volumes:
  db_data:
  mongo_data: