name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Déclenchement sur les pushes sur la branche principale
  pull_request:
    branches:
      - main  # Déclenchement sur les pull requests vers la branche principale

jobs:
  build:
    runs-on: ubuntu-latest  # Utilise l'image de base Ubuntu

    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_USER: root
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}  # Utilisation des secrets
          MYSQL_DATABASE: hairdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -h localhost" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 3

      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.adminCommand(\"ping\")'" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Mettez à jour la version

      - name: Set up Python
        uses: actions/setup-python@v3  # Mettez à jour la version
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r ./api/requirements.txt

      - name: Run tests
        env:
          DATABASE_URL: mysql+pymysql://root:${{ secrets.MYSQL_PASSWORD }}@db:3306/hairdb
          MONGO_URI: mongodb://mongo:27017  # Utilisation du nom du service MongoDB
        run: |
          pytest ./api/tests  # Adaptez le chemin des tests selon votre structure

      - name: Build Docker containers
        run: |
          docker-compose build

      - name: Start Docker containers
        run: |
          docker-compose up -d

      - name: Wait for services to be healthy
        run: |
          # Attend que les services MySQL et MongoDB soient en bonne santé
          docker-compose exec mongo bash -c 'until mongo --eval "db.adminCommand(\"ping\")"; do sleep 1; done;'
          docker-compose exec db bash -c 'until mysqladmin ping -h "localhost"; do sleep 1; done;'

      - name: Run application tests
        run: |
          curl -f http://localhost:8000/health  # Exemple d'appel d'API pour vérifier que l'application fonctionne

      - name: Stop Docker containers
        run: |
          docker-compose down
